// Mocks generated by Mockito 5.4.6 from annotations
// in backbase_sesnosr_app/test/unit/controllers/dashboard_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:backbase_sesnosr_app/core/platform/device_info_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;


/// A class which mocks [DeviceInfoService].
class MockDeviceInfoService extends _i1.Mock implements _i2.DeviceInfoService {
  MockDeviceInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getDeviceName() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceName, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getDeviceName, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> getOSVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getOSVersion, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getOSVersion, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<int> getBatteryLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getBatteryLevel, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
