// Mocks generated by Mockito 5.4.6 from annotations
// in backbase_sesnosr_app/test/unit/controllers/dashboard_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:backbase_sesnosr_app/core/platform/interfaces/device_info_service_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DeviceInfoServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoServiceInterface extends _i1.Mock
    implements _i2.DeviceInfoServiceInterface {
  MockDeviceInfoServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getDeviceName() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceName, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getDeviceName, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> getOSVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getOSVersion, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getOSVersion, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<int> getBatteryLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getBatteryLevel, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
