// Mocks generated by Mockito 5.4.6 from annotations
// in backbase_sesnosr_app/test/unit/controllers/sensor_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:backbase_sesnosr_app/core/platform/sensor_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SensorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorService extends _i1.Mock implements _i2.SensorService {
  MockSensorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Map<String, double>> get gyroscopeEvents =>
      (super.noSuchMethod(
            Invocation.getter(#gyroscopeEvents),
            returnValue: _i3.Stream<Map<String, double>>.empty(),
          )
          as _i3.Stream<Map<String, double>>);

  @override
  _i3.Future<void> toggleFlashlight(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFlashlight, [status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
